### ISSUE TITLE
Possible crash due to incompatability with Embeddium

### ISSUE THREAD

**Issue by Infestidos** [FirEmerald/DynamicVerticalSlabsAndStairs#53]
[crash-2023-12-10_16.25.31-client.txt](https://github.com/FirEmerald/AdditionalPlacements/files/13629576/crash-2023-12-10_16.25.31-client.txt)

**Comment by mimi-min** [comment]
I don't think it's due to Embeddium, I tried it on a profile with just Embeddium/related mods and it worked fine. 

Also, your crash log mentions a handful of mods, such as the Undergarden, and Snow! Real Magic; the latter of which I also use _seemingly_ without issue; I haven't tried the Undergarden yet. At any rate, I don't think Embeddium is the issue.

**Comment by Infestidos** [comment]
Odd, I was only experiencing crashing when Embeddium was installed. Rubidium saw no crashes. Thanks for looking into it anyways
