### ISSUE TITLE
Slabs not viable for verticality

### ISSUE THREAD

**Issue by InterruptingOctopus** [FirEmerald/DynamicVerticalSlabsAndStairs#8]
specifically, applied energistics and quark's slabs.
im not fully aware how the mod adds compatibility, however my hypothesis is that it grabs slabs with the minecraft:slab tag.
this would explain why the AE2 slabs dont function as according to optifine's advanced tool tips feature shows they're lacking such an identifier, however quark's slabs contain this tag yet cant be placed vertically through your mod.
i do have another hypothesis as to why this is, as quark adds vertical variants itself via the crafting table. personally im not a fan of this method and thus keep such features disabled.

Edit: another mod that isnt receiving vertical variants seems to be immersive engineering, of which i dont understand at all because the blocks seem to have ``minecraft:slab`` as well.

**Comment by FirEmerald** [comment]
It actually isn't looking for the "minecraft:slab" tag at all, it's looking for instances of SlabBlock and StairBlock, since the mixins used to enable the extended placement logic are specifically applied to those blocks.
I'm not fully certain why quark's slabs don't work but I'm highly suspicious it has to do with the quite frankly incorrect way they register their blocks.

**Comment by FirEmerald** [comment]
didn't mean to close it lol

**Comment by FirEmerald** [comment]
fixed as of [93b47f99f6076ae1d3571fefac37be7e1e926993](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/93b47f99f6076ae1d3571fefac37be7e1e926993) and [26640f4ee19a11cef90914973169029b228ae3d1](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/26640f4ee19a11cef90914973169029b228ae3d1)
