### ISSUE TITLE
adding mod to blacklist causes crash

### ISSUE THREAD

**Issue by G93d14** [FirEmerald/DynamicVerticalSlabsAndStairs#92]
https://mclo.gs/2Qty9TL 
I added the namespace of the mod in question to the blacklist. is that not how it is supposed to be added?

the mod in question was https://www.curseforge.com/minecraft/mc-mods/macaws-for-terrafirmacraft

**Comment by G93d14** [comment]
never mind i missed a quote

**Comment by FirEmerald** [comment]
Yep, and for future reference if you see "Failed loading config file" as the crash exception, it means you have a bad config file, and no mod has actually errored. the error will say what file was wrong, and further down the stacktrace will be something like "Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid value: mcwtfcaio" which will tell you what the actual error was
